-- ============================================================
-- Setup de base de datos: Plana Docente
-- Posgrado Educación UNMSM — pegar completo en el SQL Editor de Supabase
-- y ejecutar UNA sola vez.
--
-- "lineas_investigacion" es un array de texto (text[]) — cada línea de
-- investigación es un elemento, igual que el arreglo que ya tenías en
-- data/planaDocente.js. "orden" controla el orden de aparición en la
-- lista (los números más bajos van primero); se sembró con el mismo
-- orden en que ya estaban en el código.
--
-- El cruce "¿en qué programa dicta este docente?" (data/docentesPorPrograma.js)
-- sigue funcionando igual: se sigue calculando en el navegador cruzando
-- esta tabla con los horarios de data/matricula.js (eso no se movió a
-- base de datos, no hacía falta).
--
-- Se deja sembrada la misma información que ya estaba en el código
-- (data/planaDocente.js, 59 docentes), así el sitio no queda vacío apenas
-- se corre esto.
-- ============================================================

create table plana_docente (
  id uuid primary key default gen_random_uuid(),
  codigo text,
  apellidos text not null,
  nombres text not null,
  grado text,
  categoria text,
  orcid text,
  renacyt text,
  grupo_investigacion text,
  lineas_investigacion text[] not null default '{}',
  biodata text,
  orden integer not null default 0,
  created_at timestamptz default now()
);

alter table plana_docente enable row level security;

create policy "lectura publica plana docente" on plana_docente for select using (true);

create policy "admin escribe plana docente" on plana_docente for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Bucket público para el CV/biodata que el admin suba directo desde el
-- panel (además de poder simplemente pegar un link externo, como los de
-- Drive que ya se usaban).
insert into storage.buckets (id, name, public) values ('plana-docente-archivos', 'plana-docente-archivos', true);

create policy "lectura publica de archivos de plana docente" on storage.objects for select
  using (bucket_id = 'plana-docente-archivos');
create policy "admin sube archivos de plana docente" on storage.objects for insert
  with check (bucket_id = 'plana-docente-archivos' and auth.role() = 'authenticated');

-- Contenido ya existente (data/planaDocente.js), migrado tal cual.
insert into plana_docente (codigo, apellidos, nombres, grado, categoria, orcid, renacyt, grupo_investigacion, lineas_investigacion, biodata, orden) values
  ('0A3047', 'Fuster Guillen', 'Doris Elida', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0002-7889-2243', 'RENACYT NIVEL II', 'Grupo de Investigación e Innovación para la Transformación Social - GRIITS', ARRAY['Educación intercultural y bilingüe', 'Tutoría educativa', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Formación en investigación', 'Responsabilidad social universitaria en educación', 'Gestión integral de riesgo y desastres en educación'], 'https://drive.google.com/open?id=1EqI6xpUT3DRLY6yHHJeSxzh1g7VoMN0y', 1),
  ('OA5934', 'Santos Jimenez', 'Ofelia Carmen', 'Doctor (a)', 'Principal - Tiempo completo', '0000-0003-1294-0641', 'RENACYT NIVEL V', 'Educación Comparada - EDUCOMP', ARRAY['Educación intercultural y bilingüe', 'Tutoría educativa', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Gestión en educación física y deporte', 'TIC e inteligencia artificial en educación', 'Educación comparada', 'Formación en investigación'], 'https://drive.google.com/open?id=1DirRODHP5BAmbQeXV-FTipqfskn50rEg', 2),
  ('OA7549', 'Menacho Vargas', 'Isabel', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0001-6246-4618', 'RENACYT NIVEL II', 'Conocimiento y Desarrollo - CD', ARRAY['Neurociencias y aprendizaje', 'TIC e inteligencia artificial en educación'], 'https://drive.google.com/open?id=1DFJI2fkA8bq-h2IMygNXgdjyorExdXlb', 3),
  ('0A5919', 'Salvatierra Melgar', 'Angel', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0003-2817-630X', 'RENACYT NIVEL V', 'Conocimiento y Desarrollo - CD', ARRAY['Currículo, pedagogía y didáctica', 'Educación de adultos', 'Juego, recreación y tiempo libre', 'TIC e inteligencia artificial en educación', 'Formación en investigación'], 'https://drive.google.com/open?id=18t_7vFPtv454rldfB-FsU1Fg9SF3rCSb', 4),
  ('0A5320', 'Aguirre Chavez', 'Felipe', 'Doctor (a)', 'Asociado - Tiempo parcial', '0000-0003-3474-2603', 'RENACYT NIVEL VI', 'La educación holística, la educación del futuro - Amase', ARRAY['Educación intercultural y bilingüe', 'Formación en investigación'], 'https://drive.google.com/open?id=1ejoRif3DcQpORywk57atAaHbNcQEj5el', 5),
  ('059323', 'Rivera-Muñoz', 'Jorge Leoncio', 'Doctor (a)', 'Principal - Tiempo completo', '0000-0002-8202-0691', 'RENACYT NIVEL VI', 'Conocimiento y Desarrollo - CD', ARRAY['Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Educación comparada', 'Formación en investigación', 'Responsabilidad social universitaria en educación', 'Gestión integral de riesgo y desastres en educación'], 'https://drive.google.com/open?id=1W4vmwGR-9GqVRCxur9-j2nf9P7RHC0-3', 6),
  ('061085', 'Rojas Silva', 'Pedro Rodolfo', 'Magíster o Maestro (a)', 'Asociado - Tiempo completo', '0000-0003-3024-7293', null, 'Conocimiento y Desarrollo - CD', ARRAY['Gestión en educación, educación física y deporte', 'Gestión integral de riesgo y desastres en educación'], 'https://drive.google.com/open?id=1kaVb2b4ZYUnkooVc2CPTFgiOXeTWqVCb', 7),
  ('090557', 'Chauca Vidal', 'Fidel Antonio', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0002-6235-8097', null, 'Investigación en Didáctica de las Matemáticas - INDIMAT', ARRAY['Currículo, pedagogía y didáctica'], 'https://drive.google.com/open?id=1nCFvZB-7AyIMsyqXXpg900D0YfBXz_7o', 8),
  ('091936', 'Giles Nonalaya', 'Modesto Isidoro', 'Magíster o Maestro (a)', 'Asociado - Tiempo parcial', '0000-0002-0602-5568', null, 'Investigación en Didáctica de las Matemáticas - INDIMAT', ARRAY['Currículo, pedagogía y didáctica'], 'https://drive.google.com/open?id=1JFctRW8LoCMr6ad12Hyd_MaIRCsDIcCG', 9),
  ('0A7346', 'Martin Vergara', 'Joseph Santiago', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo parcial', '0000-0001-9565-9913', null, 'La educación holística, la educación del futuro - Amase', ARRAY['Educación intercultural y bilingüe', 'Currículo, pedagogía y didáctica'], 'https://drive.google.com/open?id=1iSaq98HuS0cjX-3pfGfc587hALGvgdHc', 10),
  ('0A5918', 'Nuñez Lira', 'Luis Alberto', 'Doctor (a)', 'Asociado - Dedicación exclusiva', '0000-0003-3542-9117', 'RENACYT NIVEL III', 'Conocimiento y Desarrollo - CD', ARRAY['Políticas educativas', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje', 'Formación en investigación'], 'https://drive.google.com/open?id=1746KkBxxc43RPerXFYtiMat6NCqcBZ9w', 11),
  ('0A5326', 'Escuza Mesías', 'César Daniel', 'Doctor (a)', 'Asociado - Dedicación exclusiva', '0000-0003-2150-1173', null, 'Investigaciones en la Educación Física - EDUMOT', ARRAY['Educación especial e inclusiva', 'Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje', 'Educación de adultos', 'Actividad física y deporte para la salud', 'Gestión en educación, educación física y deporte', 'Motricidad humana', 'Juego, recreación y tiempo libre', 'Formación en investigación', 'Responsabilidad social universitaria en educación'], 'https://drive.google.com/open?id=19kO-8-oijYH2y96mabzVG5U0JKXZdjHG', 12),
  ('0A 06609', 'Torres Acosta', 'Christian Sair', 'Doctor (a)', 'Auxiliar - Tiempo completo', '0000-0002-5551-4805', null, null, ARRAY['Neurociencias y aprendizaje', 'Actividad física y deporte para la salud', 'Motricidad humana', 'Juego, recreación y tiempo libre', 'Formación en investigación'], 'https://drive.google.com/open?id=1V9kA83UzM9qcuQlibzn9Y4K51A4aGcjG', 13),
  ('0A4118', 'Alcaide Aranda', 'Lourdes Ivonne del Carmen', 'Doctor (a)', 'Asociado - Tiempo parcial', '0000-0003-0304-8344', 'RENACYT NIVEL VI', null, ARRAY['Políticas educativas', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Gestión en educación, educación física y deporte', 'Educación comparada', 'Formación en investigación'], 'https://drive.google.com/open?id=1gQUiSTw23nXpTnpoCyvElLMiutUP8Yu6', 14),
  ('0A9108', 'Vásquez Colichón', 'Aleida Eliana', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo parcial', '0000-0001-7826-037X', null, null, ARRAY['Educación intercultural y bilingüe', 'Políticas educativas', 'Currículo, pedagogía y didáctica', 'Educación de adultos', 'Gestión en educación, educación física y deporte', 'TIC e inteligencia artificial en educación', 'Formación en investigación'], 'https://drive.google.com/open?id=1qT1SLslVlfMkwcJJg4U1v0PVbOlUQJxY', 15),
  ('0A0400', 'Velarde Consoli', 'Esther Mariza', 'Doctor (a)', 'Principal - Tiempo completo', '0000-0003-0182-4362', null, 'Estimulación de las funciones cognitivas y psicolingüísticas en niños del nivel de primaria en el Perú - EDUKPRIM', ARRAY['Educación intercultural y bilingüe', 'Educación especial e inclusiva', 'Evaluación y calidad educativa', 'Neurociencias y aprendizaje'], 'https://drive.google.com/open?id=1VtmVRdapvX2Eu_qTD1_g64U736FXYk3J', 16),
  ('0A7349', 'Benavente Ayquipa', 'Rosa Maria', 'Doctor (a)', 'Auxiliar - Tiempo parcial', '0000-0001-7663-1720', null, 'La educación holística, la educación del futuro - Amase', ARRAY['Currículo, pedagogía y didáctica'], 'https://drive.google.com/open?id=14EjsHT6sIbjXXSL8ar9zazyWQD3auBto', 17),
  ('0A5323', 'Diaz Barboza', 'Miguel Aquilino', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0001-5665-8766', null, 'Ciencias de la Motricidad, Actividad Física y Deporte - MACFIDE', ARRAY['Currículo, pedagogía y didáctica', 'Actividad física y deporte para la salud', 'Responsabilidad social universitaria en educación'], 'https://drive.google.com/open?id=13A6Y7Sc_iC1EXGYAkxkoYcLndu18g3tW', 18),
  ('0A7345', 'Ayala Falcón', 'Eloy Eladio', 'Doctor (a)', 'Auxiliar - Tiempo parcial', '0000-0002-7592-5134', 'RENACYT NIVEL I', 'La educación holística, la educación del futuro - Amase', ARRAY['Evaluación y calidad educativa', 'Formación en investigación'], 'https://drive.google.com/open?id=1WgLERtElFlKi115qOTl3DX2ifv1J--X4', 19),
  ('0A7587', 'De la Cruz Ordoñez', 'Ada Justa', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo parcial', '0000-0002-1959-1627', 'RENACYT NIVEL I', 'Investigaciones en la Educación Física - EDUMOT', ARRAY['Evaluación y calidad educativa'], 'https://drive.google.com/open?id=1hX1metHk3E9uqp9nTub_mACI4_wiaYof', 20),
  ('0A7347', 'Saavedra Jaramillo', 'Milagritos Josefina', 'Doctor (a)', 'Auxiliar - Tiempo parcial', '0000-0001-7137-5836', null, 'Grupo de Investigación e Innovación para la Transformación Social - GRIITS', ARRAY['TIC e inteligencia artificial en educación'], 'https://drive.google.com/open?id=1xauhCfDClxRzjnsJT6EkuBbwiTeNZpgQ', 21),
  ('0A2056', 'Carrillo Vásquez', 'Elí Romeo', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0003-4460-6808', 'RENACYT NIVEL VII', 'Investigando para Educar - IPE', ARRAY['Políticas educativas', 'Currículo, pedagogía y didáctica', 'TIC e inteligencia artificial en educación'], 'https://drive.google.com/open?id=1M4NVn9zkPyoG5GsZzUqEuT5OwzK4G0Oe', 22),
  ('0A1853', 'Berrocal Villegas', 'Salomón Marcos', 'Doctor (a)', 'Asociado - Dedicación exclusiva', '0000-0002-6320-2342', 'RENACYT NIVEL VI', 'Influencia del Docente en el Rendimiento Académico del Alumno - INDOREAC', ARRAY['Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje', 'TIC e inteligencia artificial en educación', 'Formación en investigación'], 'https://drive.google.com/open?id=1iNWDB20TD4hjzNstYnD9KO-kDSmys3fr', 23),
  ('0A5327', 'Arista Huaco', 'Manuel Jesus', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo parcial', '0000-0002-1639-5372', null, null, ARRAY['Currículo, pedagogía y didáctica', 'TIC e inteligencia artificial en educación'], 'https://drive.google.com/open?id=1N77E9Dgh0Fd8SlRm3vE3FVlCNCmQuqpe', 24),
  ('O11681', 'Candela Linares', 'Hugo Máximo', 'Magíster o Maestro (a)', 'Asociado - Tiempo completo', '0000-0002-1020-4301', null, 'Educación Comparada - EDUCOMP', ARRAY['Currículo, pedagogía y didáctica', 'Educación de adultos', 'Educación comparada'], 'https://drive.google.com/open?id=1AvgIHFXRNtpEOMUu_B6QHf2zxOhQR7C8', 25),
  ('OA 5322', 'Rivsplata Varilla', 'Paula Ermila', 'Doctor (a)', 'Auxiliar - Tiempo completo', '0000-0001-7036-6436', 'RENACYT NIVEL II', null, ARRAY['Gestión integral de riesgo y desastres en educación'], 'https://drive.google.com/open?id=1pcbuKq8LfeGJcw8IudeFM2z1F40rmuPz', 26),
  ('0A5316', 'Encalada Díaz', 'Iván Ángel', 'Doctor (a)', 'Auxiliar - Tiempo completo', '0000-0001-5596-5713', null, 'Estimulación de las funciones cognitivas y psicolingüísticas en niños del nivel de primaria en el Perú - EDUKPRIM', ARRAY['Evaluación y calidad educativa', 'Neurociencias y aprendizaje', 'Educación de adultos', 'Gestión en educación', 'TIC e inteligencia artificial en educación', 'Educación comparada', 'Formación en investigación', 'Responsabilidad social universitaria en educación'], 'https://drive.google.com/open?id=1CtPgZHhWb1vzso3Vx-MFtAFLKYPQFpRU', 27),
  ('0A7348', 'Sedamano Ballesteros', 'Manuel Alberto', 'Doctor (a)', 'Asociado - Tiempo parcial', '0000-0003-3458-6452', 'RENACYT NIVEL VII', 'Grupo de Investigación e Innovación para la Transformación Social - GRIITS', ARRAY['Educación intercultural y bilingüe', 'Educación especial e inclusiva', 'Tutoría educativa', 'Políticas educativas', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje', 'Gestión en educación', 'TIC e inteligencia artificial en educación'], 'https://drive.google.com/open?id=1felApaWojq1-ocTTH8D63VEf62kHa7WN', 28),
  ('048402', 'Nuñez Flores', 'María Isabel', 'Doctor (a)', 'Principal - Tiempo completo', '0000-0001-7989-7110', null, 'Perspectivas de la Educación - EDUCACIN', ARRAY['TIC e inteligencia artificial en educación'], 'https://drive.google.com/open?id=1qZitd_zdxxNP1ilnMONqk62w8woxPAj9', 29),
  ('0A1818', 'Vildoso Villegas', 'Jesahel Yanette', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0002-4950-2453', 'RENACYT NIVEL VI', 'Educación de Calidad - Métodos', ARRAY['Evaluación y calidad educativa'], 'https://drive.google.com/open?id=1jjOUCMmgVtI8N092Xf8ljzxoWmK8vog9', 30),
  ('0A0401', 'Flores Urpe', 'María Luisa', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0003-4306-8657', null, 'Educación Comparada - EDUCOMP', ARRAY['Motricidad humana', 'TIC e inteligencia artificial en educación', 'Educación comparada', 'Responsabilidad social universitaria en educación'], 'https://drive.google.com/open?id=11DBtQ0PmoVPKPpGRMAlWGsDWarmqQlGw', 31),
  ('0A9104', 'Aguinaga Villegas', 'Dante Rafael', 'Doctor (a)', 'Auxiliar - Tiempo completo', '0000-0001-5166-0509', 'RENACYT NIVEL VII', 'Investigación en Didáctica de las Matemáticas - INDIMAT', ARRAY['Tutoría educativa', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Educación de adultos', 'Gestión en educación', 'TIC e inteligencia artificial en educación', 'Responsabilidad social universitaria en educación'], 'https://drive.google.com/open?id=1BS0789CPhJyM2JG1bPv6Kv7AXYi4nkG0', 32),
  ('0A5914', 'Alarcon Diaz', 'Mitchell Alberto', 'Doctor (a)', 'Principal - Dedicación exclusiva', '0000-0003-0027-5701', 'RENACYT NIVEL V', 'Investigaciones en la Educación Física - EDUMOT', ARRAY['Currículo, pedagogía y didáctica', 'Gestión en educación física y deporte', 'Formación en investigación'], 'https://drive.google.com/open?id=1Kkuwx74JmQBdfOv_Y7wiRjZ7zyINfuA7', 33),
  ('0A7577', 'Palomino Paredes', 'Juan Carlos', 'Doctor (a)', 'Auxiliar - Tiempo parcial', '0000-0001-5333-9516', null, null, ARRAY['Políticas educativas'], 'https://drive.google.com/open?id=1XUV2cQh2i3_Mv1n0FoD5uttAce6AYWb3', 34),
  ('0A4124', 'Colque Ricce', 'Oscar Alfredo', 'Doctor (a)', 'Auxiliar - Tiempo completo', '0000-0002-5023-0037', 'RENACYT NIVEL I', 'Educación de Calidad - Métodos', ARRAY['Educación especial e inclusiva', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje', 'Educación de adultos', 'Actividad física y deporte para la salud', 'Gestión en educación', 'Juego, recreación y tiempo libre', 'Formación en investigación'], 'https://drive.google.com/open?id=15OiNRGSbajN274lZUp26_0_F1VY_Agfq', 35),
  ('0A5920', 'Soto Zedano', 'Freddy Alejandro', 'Magíster o Maestro (a)', 'Asociado - Dedicación exclusiva', '0000-0001-9244-6445', 'RENACYT NIVEL VII', 'Ciencias de la Motricidad, Actividad Física y Deporte - MACFIDE', ARRAY['Actividad física y deporte para la salud'], 'https://drive.google.com/open?id=1hEdcAKbdstWMV0LdAW9t9tcVFK-DXuEk', 36),
  ('0A5916', 'Palacios Garay', 'Jessica Paola', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0002-2315-1683', 'RENACYT NIVEL II', 'La educación holística, la educación del futuro - Amase', ARRAY['Educación especial e inclusiva', 'Tutoría educativa', 'Formación en investigación', 'Responsabilidad social universitaria en educación'], 'https://drive.google.com/open?id=18EEVrS7-Nq2zUjq8B8jqHrRi_4n_3dAv', 37),
  ('0A7576', 'Ortiz Treviños', 'Wilson Marcos', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo completo', '0000-0002-2105-7909', null, null, ARRAY['Educación intercultural y bilingüe', 'Tutoría educativa', 'Políticas educativas', 'Evaluación y calidad educativa'], 'https://drive.google.com/open?id=1JAVftaxeMDko7RGbB2bNcwXfgsN7DQwK', 38),
  ('0A5913', 'Vílchez Huerto', 'Ana María Isabel', 'Doctor (a)', 'Principal - Tiempo completo', '0000-0003-4666-3830', null, 'La educación holística, la educación del futuro - Amase', ARRAY['Educación intercultural y bilingüe', 'Currículo, pedagogía y didáctica', 'Gestión en educación', 'Formación en investigación'], 'https://drive.google.com/open?id=1zNNeDzZcT7D2Jy3-FNxGAz1_kgWAfv-2', 39),
  ('OA9105', 'Galvez Suarez', 'Eric', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo parcial', '0000-0002-7642-5019', 'RENACYT NIVEL VII', null, ARRAY['Tutoría educativa', 'Políticas educativas', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Gestión en educación', 'TIC e inteligencia artificial en educación'], 'https://drive.google.com/open?id=1gAIQKQwf7nEuhlg8tKtjcJ6xlffmxIjH', 40),
  ('0A5328', 'Tejada Mendoza', 'Marco Antonio', 'Doctor (a)', 'Asociado - Dedicación exclusiva', '0000-0003-0881-6613', null, 'Investigaciones en la Educación Física - EDUMOT', ARRAY['Educación especial e inclusiva', 'Tutoría educativa', 'Políticas educativas', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje', 'Educación de adultos', 'Actividad física y deporte para la salud', 'Gestión en educación, educación física y deporte', 'Motricidad humana', 'Juego, recreación y tiempo libre', 'TIC e inteligencia artificial en educación', 'Educación comparada', 'Formación en investigación', 'Responsabilidad social universitaria en educación', 'Gestión integral de riesgo y desastres en educación'], 'https://drive.google.com/open?id=1vuXFKKI0LS9hGuCtvQlvgcZbnJlgHWj4', 41),
  ('0A5324', 'Soria Villanueva', 'Lucia Mireya', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo parcial', '0000-0002-5487-4171', 'RENACYT NIVEL I', 'Ciencias de la Motricidad, Actividad Física y Deporte - MACFIDE', ARRAY['Actividad física y deporte para la salud'], 'https://drive.google.com/open?id=1yo6784V822UYKhW1selPxpui-LM4qfbL', 42),
  ('0A0399', 'Cruz Shuan', 'Reyna Luisa', 'Doctor (a)', 'Asociado - Dedicación exclusiva', '0000-0003-4466-0257', null, 'Aportes de los profesores de la Facultad de Educación en la formación docente UNMSM - Maestros', ARRAY['Educación especial e inclusiva', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Gestión en educación', 'Formación en investigación', 'Responsabilidad social universitaria en educación', 'Gestión integral de riesgo y desastres en educación'], 'https://drive.google.com/open?id=193f_9dqMwz8b-pOWVjoTthqoHKUy8Zhp', 43),
  ('0A5321', 'Garnelo Escobar', 'Ronal Rodolfo', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo parcial', '0000-0002-5180-8654', null, null, ARRAY['Educación intercultural y bilingüe', 'Políticas educativas', 'Gestión en educación'], 'https://drive.google.com/open?id=1kQCMmCv2elu0NJX-yr9i_hDYoan-J43z', 44),
  ('0A1447', 'Campana Concha', 'Abelardo Rodolfo', 'Doctor (a)', 'Principal - Tiempo completo', '0000-0002-1098-9508', 'RENACYT NIVEL III', 'Educiencia - EC', ARRAY['Evaluación y calidad educativa', 'Actividad física y deporte para la salud', 'Gestión en educación', 'Gestión en educación física y deporte', 'Motricidad humana', 'Formación en investigación', 'Responsabilidad social universitaria en educación'], 'https://drive.google.com/open?id=16XyEGrYbUl7giUBxzBHItVoq238Bwe4b', 45),
  (null, 'Gomez', 'Robles', 'Magíster o Maestro (a)', 'Contratado', '0000-0002-0748-7478', null, null, ARRAY['Educación de adultos'], 'https://drive.google.com/open?id=13VcJHVmYlcsKRjdWVN4_GTc6tPXWTv-A', 46),
  ('0A5319', 'Oseda Gago', 'Dulio', 'Doctor (a)', 'Asociado - Tiempo parcial', '0000-0002-3136-6094', 'RENACYT NIVEL II', 'La educación holística, la educación del futuro - Amase', ARRAY['Educación intercultural y bilingüe', 'Educación especial e inclusiva', 'Tutoría educativa', 'Políticas educativas', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje', 'Educación de adultos', 'Actividad física y deporte para la salud', 'Gestión en educación, educación física y deporte', 'Motricidad humana', 'Juego, recreación y tiempo libre', 'TIC e inteligencia artificial en educación', 'Educación comparada', 'Formación en investigación', 'Responsabilidad social universitaria en educación', 'Gestión integral de riesgo y desastres en educación'], 'https://drive.google.com/open?id=13b66mZ8gM3nYE3g2a6skS24zx3snAVrR', 47),
  ('0A7579', 'Fuentes Avila', 'Xavier', 'Doctor (a)', 'Auxiliar - Tiempo completo', '0000-0001-7287-9892', null, 'Investigaciones en la Educación Física - EDUMOT', ARRAY['Actividad física y deporte para la salud', 'Motricidad humana', 'Juego, recreación y tiempo libre'], 'https://drive.google.com/open?id=1cZUpKT37q_YuKek7vKx_XRxdSX8wk54J', 48),
  ('038709', 'Loayza Loayza', 'Juan', 'Magíster o Maestro (a)', 'Asociado - Tiempo completo', '0000-0002-2829-8094', null, 'Perspectivas de la Educación - EDUCACIN', ARRAY['Currículo, pedagogía y didáctica'], 'https://drive.google.com/open?id=1Za1zQnwx9NZGqoOCJ3Z-vGX3Aibh22U9', 49),
  ('0A2054', 'Vigil Guerrero', 'Luz Roxana', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0003-2539-9049', null, 'La educación holística, la educación del futuro - Amase', ARRAY['Educación intercultural y bilingüe', 'Currículo, pedagogía y didáctica', 'Gestión integral de riesgo y desastres en educación'], 'https://drive.google.com/open?id=1mVUk3uNEmj21IQKH0sMUN1eOhKLINO-D', 50),
  ('0A2182', 'Sanchez Garcia', 'Tula Carola', 'Doctor (a)', 'Principal - Dedicación exclusiva', '0000-0002-6064-8891', 'RENACYT NIVEL VI', 'Ciencia Tecnología y Sociedad - CITECSO', ARRAY['Currículo, pedagogía y didáctica', 'TIC e inteligencia artificial en educación'], 'https://drive.google.com/open?id=1vec4ky0YyHYgrtylHLNbE2kKUiJKhkhq', 51),
  ('0A1970', 'Dextre Mendoza', 'Carlos Wyly', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0003-1360-739X', 'RENACYT NIVEL VI', 'Ciencias de la Motricidad, Actividad Física y Deporte - MACFIDE', ARRAY['Currículo, pedagogía y didáctica', 'Actividad física y deporte para la salud', 'Motricidad humana', 'Formación en investigación', 'Gestión integral de riesgo y desastres en educación'], 'https://drive.google.com/open?id=1nYP-7sD4uQvyuvVkL8qfX4J-kL-eDovD', 52),
  ('0A0073', 'Jacinto Pazo', 'Pedro Maguín', 'Doctor (a)', 'Principal - Tiempo completo', '0000-0003-2965-9258', null, null, ARRAY['Educación intercultural y bilingüe', 'Gestión en educación', 'Educación comparada', 'Formación en investigación'], 'https://drive.google.com/open?id=1TdFyBlAccjL9_3AJhK2Y03WiI9kPL-oT', 53),
  ('0A2424', 'Isla Alcoser', 'Sandy Dorian', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0003-1330-3716', 'RENACYT NIVEL V', 'Grupo de Investigación Especializado en Pedagogía del Deporte - IESPORTE', ARRAY['Políticas educativas', 'Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje', 'Actividad física y deporte para la salud', 'Gestión en educación física y deporte', 'Motricidad humana', 'Juego, recreación y tiempo libre'], 'https://drive.google.com/open?id=182DieLyI_0BNs--6dS2RX7dbF13M4ME2', 54),
  ('093718', 'Chavez Alvan', 'Luis Martin', 'Magíster o Maestro (a)', 'Asociado - Tiempo completo', '0000-0002-1196-3422', null, 'Investigaciones en la Educación Física - EDUMOT', ARRAY['Actividad física y deporte para la salud'], 'https://drive.google.com/open?id=1_eYRHKkoZOOeU374f2Tl3DqZhxCSH5PJ', 55),
  ('OA 7574', 'Baez Rodríguez', 'Lilia Lucía', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo parcial', '0000-0002-3929-8698', null, 'Aportes de los profesores de la Facultad de Educación en la formación docente UNMSM - Maestros', ARRAY['Currículo, pedagogía y didáctica'], 'https://drive.google.com/open?id=1-4sE3WoFDXsXi1FKOFW8vUX3DSnpOyf7', 56),
  ('0A2055', 'Díaz Flores', 'Francis', 'Doctor (a)', 'Asociado - Tiempo completo', '0000-0002-9272-9995', 'RENACYT NIVEL VI', 'Educiencia - EC', ARRAY['Políticas educativas', 'Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Formación en investigación'], 'https://drive.google.com/open?id=1BY_wz-GLDxjeIfxaQvJzXxXP_WnIzMPc', 57),
  ('0A7575', 'Garay Ramirez', 'Sthefani Elena', 'Magíster o Maestro (a)', 'Auxiliar - Tiempo parcial', '0000-0002-0750-4346', null, 'Aportes de los profesores de la Facultad de Educación en la formación docente UNMSM - Maestros', ARRAY['Evaluación y calidad educativa', 'Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje', 'TIC e inteligencia artificial en educación'], 'https://drive.google.com/open?id=1ZJ9ixbMGdVf5tfs6qcoylUqtNwigt_Oc', 58),
  ('0A7573', 'Alata Cusy', 'Yudith Ivonne', 'Doctor (a)', 'Asociado - Dedicación exclusiva', '0000-0001-9123-976X', null, 'La educación holística, la educación del futuro - Amase', ARRAY['Tutoría educativa', 'Currículo, pedagogía y didáctica', 'Neurociencias y aprendizaje'], 'https://drive.google.com/open?id=1gD4wTxe0uyhXktzn5z1oUTFo15IvNJtz', 59);
